name: Push to Replicate
on:
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Cog
      run: |
        curl -o install_cog.sh https://replicate.github.io/cog/install.sh
        bash install_cog.sh
        echo "PATH=$PATH:/usr/local/bin" >> $GITHUB_PATH
        export PATH=$PATH:/usr/local/bin
    - name: Check cog version (debug step)
      run: |
        echo "Current PATH: $PATH"
        which cog || echo "cog command not found"
        /usr/local/bin/cog --version || echo "Failed to run cog --version"
    - name: Log in to Replicate
      run: |
        /usr/local/bin/cog login --token ${{ secrets.REPLICATE_API_TOKEN }}
    - name: Push to Replicate
      run: |
        /usr/local/bin/cog push r8.im/timosan61/fantasy-talking-tim
