name: Push to Replicate
on:
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Cog via npm
      run: |
        npm install -g @replicate/cog
        cog --version
    - name: Log in to Replicate
      run: |
        cog login --token ${{ secrets.REPLICATE_API_TOKEN }}
    - name: Push to Replicate
      run: |
        cog push r8.im/timosan61/fantasy-talking-tim
