name: Push to Replicate
on:
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Cog
      run: |
        python -m pip install --upgrade pip
        pip install replicate-cog
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Check cog version (debug step)
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        python -m pip list | grep cog
        python -c "import subprocess; subprocess.run(['cog', '--version'])"
    - name: Log in to Replicate
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        python -c "import subprocess; subprocess.run(['cog', 'login', '--token', '${{ secrets.REPLICATE_API_TOKEN }}'])"
    - name: Push to Replicate
      run: |
        export PATH="$HOME/.local/bin:$PATH"
        python -c "import subprocess; subprocess.run(['cog', 'push', 'r8.im/timosan61/fantasy-talking-tim'])"
